// Command topsail is the multi-call BusyBox-like binary entry point.
//
// Applets self-register in their package init() functions. To add an applet,
// create applets/<name>/, give it an init() that calls applet.Register, and
// add a blank import to the import list below.
package main

import (
	"os"

	"github.com/Real-Fruit-Snacks/topsail/internal/cli"

	// Applet imports — one line per applet package, alphabetized.
	// Each blank import runs that package's init() to self-register.
	_ "github.com/Real-Fruit-Snacks/topsail/applets/awk"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/base64"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/basename"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/cat"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/chmod"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/chown"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/column"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/comm"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/cp"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/curl"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/cut"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/date"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/df"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/dirname"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/du"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/echo"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/env"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/expr"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/factor"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/false"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/file"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/find"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/fold"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/grep"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/gzip"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/head"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/host"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/hostname"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/id"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/join"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/jq"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/ln"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/ls"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/md5sum"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/mkdir"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/mv"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/nl"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/paste"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/ping"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/printf"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/pwd"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/readlink"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/rev"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/rm"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/rmdir"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/sed"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/seq"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/sha256sum"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/sha512sum"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/shuf"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/sleep"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/sort"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/split"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/stat"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/sum"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/tac"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/tail"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/tar"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/tee"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/test"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/touch"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/tr"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/true"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/tsort"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/uname"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/uniq"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/wc"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/which"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/whoami"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/xargs"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/yes"
	_ "github.com/Real-Fruit-Snacks/topsail/applets/zip"
)

func main() {
	os.Exit(cli.Run(os.Args))
}
